name: Azure Static Web Apps CI/CDname: Azure Static Web Apps CI/CD



on:on:

  push:  push:

    branches:    branches:

      - main      - main

  pull_request:  pull_request:

    types: [opened, synchronize, reopened, closed]    types: [opened, synchronize, reopened, closed]

    branches:    branches:

      - main      - main



jobs:jobs:

  build_and_deploy_job:  build_and_deploy_job:

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')

    runs-on: ubuntu-latest    runs-on: ubuntu-latest

    name: Build and Deploy Job    name: Build and Deploy Job

    steps:    steps:

      - uses: actions/checkout@v4      - uses: actions/checkout@v3

        with:        with:

          submodules: true          submodules: true

          lfs: false          lfs: false

          # ✅ FIX: Nettoyer la config Git pour éviter l'erreur extraheader      - name: Build And Deploy

          persist-credentials: false        id: builddeploy

                  uses: Azure/static-web-apps-deploy@v1

      - name: Setup Git config        with:

        run: |          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_DUNE_0FEBC7903 }}

          git config --global --unset-all http.https://github.com/.extraheader || true          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)

          git config --global user.name "GitHub Actions"          action: "upload"

          git config --global user.email "actions@github.com"          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######

                    # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig

      - name: Build And Deploy          app_location: "/" # App source code path

        id: builddeploy          api_location: "" # Api source code path - optional

        uses: Azure/static-web-apps-deploy@v1          output_location: "" # Built app content directory - optional (Next.js handles this automatically)

        with:          ###### End of Repository/Build Configurations ######

          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_DUNE_0FEBC7903 }}        env:

          repo_token: ${{ secrets.GITHUB_TOKEN }}          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}

          action: "upload"          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

          ###### Repository/Build Configurations ######

          app_location: "/" # App source code path  close_pull_request_job:

          api_location: "" # Api source code path - optional    if: github.event_name == 'pull_request' && github.event.action == 'closed'

          output_location: "" # Built app content directory - optional    runs-on: ubuntu-latest

          ###### End of Repository/Build Configurations ######    name: Close Pull Request Job

        env:    steps:

          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}      - name: Close Pull Request

          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}        id: closepullrequest

        uses: Azure/static-web-apps-deploy@v1

  close_pull_request_job:        with:

    if: github.event_name == 'pull_request' && github.event.action == 'closed'          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_DUNE_0FEBC7903 }}

    runs-on: ubuntu-latest          action: "close"

    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_DUNE_0FEBC7903 }}
          action: "close"